spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test.crgyiukce4t8.ap-northeast-2.rds.amazonaws.com/test
    username: admin
    password: 1q2w3e4r!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql : debug